#!/bin/sh
#
# Create a new LaTeX header file for doxygen PDF docs
#
# Copyright 1998-2025 by Bill Spitzak and others.
#
# This library is free software. Distribution and use rights are outlined in
# the file "COPYING" which should have been included with this file.  If this
# file is missing or damaged, see the license at:
#
#     https://www.fltk.org/COPYING.php
#
# Please see the following page on how to report bugs and issues:
#
#      https://www.fltk.org/bugs.php
#

#
# Note: the created LaTeX file depends on Doxygen and LaTeX versions, resp. and
# must be created on the build system with the current Doxygen and version.
#
# Usage:
#
#   $ sh make_header doxygen_path input-file output-file
#
# where
# - 'doxygen_path' is the full path to the doxygen executable
#   or just 'doxygen'. If the full path is used an arbitrary
#   doxygen executable and thus doxygen version can be used.
# - 'input-file' is the pure (LaTeX) title page (template)
# - 'output-file' is the generated (LaTeX) title page (template)
#   that is used by `make' or `cmake` to generate the final LaTeX
#   page header (combined doxygen template + FLTK title page).
#
#=======================================================================
# This script requires a posix shell and uses the following commands:
# cat, rm and sed and (obviously) doxygen.
#=======================================================================
# To do: investigate if this can be simplified by using CMake directly.
# This is possible since 1.5 (we don't use configure/make anymore).
#=======================================================================

# Doxygen command, input and output file names

DOXY_CMD="$1"
FLTK_HEAD="$2"
DOXY_HEAD="$3"

# temp files

DOXY_TEMP1="doxy-temp1.tex.$$"
DOXY_TEMP2="doxy-temp2.tex.$$"

echo
echo "--- make_header $@ // $DOXY_TEMP1, $DOXY_TEMP2"
echo

if test x$FLTK_HEAD = x; then
  echo "usage: $0 fltk-header-file output-file"
  exit 1
fi

if test x$DOXY_HEAD = x; then
  echo "usage: $0 fltk-header-file output-file"
  exit 1
fi

# (1) Create the doxygen LaTeX header template and
# (2) insert LaTeX setup code before '\begin{document}' and
# (3) replace the LaTeX code between (and including) the lines containing
#     - 'begin{titlepage}' and
#     - 'end{titlepage}'
#     with our own PDF document title page (LaTeX code)
# and write the result to $DOXY_HEAD.

# (1) create standard doxygen / LaTeX template (output: $DOXY_TEMP1)

"$DOXY_CMD" -w latex $DOXY_TEMP1 /dev/null /dev/null

# (2) insert the LuaLaTeX and font setup stuff before the line
# '\begin{document}' (output: $DOXY_TEMP2)

( sed -e'/begin{document}/,$d' < $DOXY_TEMP1
  cat setup.tex
  sed -e'1,/begin{document}/d' < $DOXY_TEMP1
) > $DOXY_TEMP2

# (3) replace the doxygen standard title page with our own title page
# output: $DOXY_HEAD

( sed -e'/begin{titlepage}/,$d' < $DOXY_TEMP2
  cat $FLTK_HEAD
  sed -e'1,/end{titlepage}/d' < $DOXY_TEMP2
) > $DOXY_HEAD

# cleanup

rm -f $DOXY_TEMP1 $DOXY_TEMP2
