name: Minimal Build and Test

on: [push]

jobs:

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      working-directory: ${{github.workspace}}/build
      run: cmake ..

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config Release
